### ISSUE TITLE
Concerns Regarding Labeling Practices and Contributor Respect

### ISSUE THREAD

**Issue by Brijeshthummar02** [SjxSubham/Leetcode#20]
Message:

Adding unnecessary labels to someone’s PR, especially after they have provided a solution that has been reviewed and merged, goes against our community guidelines. As maintainers, this practice reflects a lack of guidance and respect for contributors’ efforts, undermining the supportive and collaborative environment we aim to foster.

To other contributors, I want to express my disappointment in this situation. This has been the worst experience I’ve had working on a repository. It’s disheartening to see that @SjxSubham  is more focused on personal gain than valuing the hard work of contributors. Such actions not only harm the community but also discourage collaboration and trust.

In the long term, focusing on short-term gains, like stars or badges, at the expense of contributor respect will only harm your growth and reputation within the community. True success in open source comes from meaningful contributions and fostering a positive space for all participants.

I will not be working with people who prioritize personal wealth over the efforts of others. Let’s commit to quality, transparency, and integrity as we work together to maintain this project, ensuring our actions reflect the values we wish to uphold.

I need your vote and support on this matter.
@Amisha328 , @Amisha2093  , @PralayeshMukherjee , @Taj-2005 , @Shreya-Ghanty , @AS10anjan.

above mentioned, you can check my pull req #13 for clarity.

Thanks.

**Comment by SjxSubham** [comment]
> Message:
> 
> Adding unnecessary labels to someone’s PR, especially after they have provided a solution that has been reviewed and merged, goes against our community guidelines. As maintainers, this practice reflects a lack of guidance and respect for contributors’ efforts, undermining the supportive and collaborative environment we aim to foster.
> 
> To other contributors, I want to express my disappointment in this situation. This has been the worst experience I’ve had working on a repository. It’s disheartening to see that @SjxSubham is more focused on personal gain than valuing the hard work of contributors. Such actions not only harm the community but also discourage collaboration and trust.
> 
> In the long term, focusing on short-term gains, like stars or badges, at the expense of contributor respect will only harm your growth and reputation within the community. True success in open source comes from meaningful contributions and fostering a positive space for all participants.
> 
> I will not be working with people who prioritize personal wealth over the efforts of others. Let’s commit to quality, transparency, and integrity as we work together to maintain this project, ensuring our actions reflect the values we wish to uphold.
> 
> I need your vote and support on this matter. @Amisha328 , @Amisha2093 , @PralayeshMukherjee , @Taj-2005 , @Shreya-Ghanty , @AS10anjan.
> 
> above mentioned, you can check my pull req #13 for clarity.
> 
> Thanks.

To get Your PR merged forcefully U hv given star and after getting merged, U removed the star.
And There's Issues section it's clearly mentioned that Add codes Only In Cpp, U have provided java solution.even  Though I have merged...!!!

And btw, U have already Gotten 4 PR merged for Hacktoberfest it's clearly visible on ur github profile ...
So u no need to worry , And Yah though I labeled it as invalid this Contribution will be still count in ur github profile... 


And if U want to get valid PR merged then add Code solution in Cpp with approach And I promise U this time I will Merge Ur PR and it will be valid contribution. Qnd yah It will accepted on that platform as Valid Contribution....
